# Artificial Neural Networks

### Customer retention Analytics

##### Business Problem:
An International bank collected a sample data of 10,000 customers. They observed that some of their custimers are leaving or churning in an unusually high rate and they want to find understand and access why their customers keep leaving. They have hiered you as a data scientist to look into the data to give then some insight.

##### Data:
The data was collected within the last 5 months, the feautures include the customer's name, creditscore, geography, gendey,age,tenure,balnce, number of products(accounts),credit card status(whether they have one or not), estimated salary, activity status(active member or not) and if the customer remained with them.

## Import Libraries

In [2]:
!python -m pip install --user --upgrade pip

!pip3 install pandas==0.23.4 matplotlib==3.0.3 scipy==1.2.1 scikit-learn==0.22 tensorflow==2.0 keras==1.2.2 --user

Collecting pip
  Downloading https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 2.9MB/s eta 0:00:01
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.6 are installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.2.2
WARNING: You are using pip version 19.3.1; however, version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting google-cloud-bigquery==1.6.0
  Downloading google_cloud_bigquery-1.6.0-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.1 MB/s eta 0:00:011
Collecting pandas==0.23.4
  Downloading pandas-0.23.4-cp36-cp36m-manylinux1_x86_64.whl (8.9 MB)
     |████████████████████████████████| 8.9 MB 8.3 MB/s eta 0:00:01
Collecting matplotlib==3.0.3
  Downloading matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0 MB)
     |████████████████████████████████| 13.0 MB 64.3 MB/s eta 0:00:01
Collecting scipy==1.2.1
  Downloading scipy-1.2.1-cp36-cp36m-manylinux1_x86_64.whl (24.8 MB)
     |████████████████████████████████| 24.8 MB 65.6 MB/s eta 0:00:01
Collecting scikit-learn==0.22
  Downloading scikit_learn-0.22-cp36-cp36m-manylinux1_x86_64.whl (7.0 MB)
     |████████████████████████████████| 7.0 MB 27.0 MB/s eta 0:00:01
Collecting tensorflow==2.0
  Downloading tensorflow-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl (86.3 MB)
     |████████████████████████████████| 86.3 MB 75 kB/s s eta 0:00:01
Collecting keras==1.2.2
  Downloading Keras-1.2.2.tar.gz (175 kB)
     |████████████████████████████████| 175 kB 72.6 MB/s eta 0:00:01
Requirement already satisfied: google-api-core<2.0.0dev,>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from google-cloud-bigquery==1.6.0) (1.16.0)
Requirement already satisfied: google-resumable-media>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-cloud-bigquery==1.6.0) (0.5.0)
Collecting google-cloud-core<0.29dev,>=0.28.0
  Downloading google_cloud_core-0.28.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from pandas==0.23.4) (1.18.1)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas==0.23.4) (2019.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas==0.23.4) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3) (2.4.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3) (1.1.0)
Collecting joblib>=0.11
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 64.4 MB/s eta 0:00:01
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (0.8.1)
Requirement already satisfied: keras-applications>=1.0.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.1.0)
Collecting tensorboard<2.1.0,>=2.0.0
  Downloading tensorboard-2.0.2-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 52.7 MB/s eta 0:00:01
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (0.1.8)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (3.11.2)
Collecting tensorflow-estimator<2.1.0,>=2.0.0
  Downloading tensorflow_estimator-2.0.1-py2.py3-none-any.whl (449 kB)
     |████████████████████████████████| 449 kB 83.7 MB/s eta 0:00:01
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.11.2)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow==2.0) (0.30.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.26.0)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (0.9.0)
Requirement already satisfied: gast==0.2.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (0.2.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (3.1.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.13.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.0) (1.1.0)
Collecting theano
  Downloading Theano-1.0.5.tar.gz (2.8 MB)
     |████████████████████████████████| 2.8 MB 50.0 MB/s eta 0:00:01
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras==1.2.2) (5.3)
Requirement already satisfied: setuptools>=34.0.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (44.0.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (2.22.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (1.51.0)
Requirement already satisfied: google-auth<2.0dev,>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (1.10.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.8->tensorflow==2.0) (2.10.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow==2.0) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow==2.0) (0.16.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow==2.0) (0.4.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (1.25.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (4.0.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow==2.0) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<4.1,>=3.1.4->google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery==1.6.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow==2.0) (3.1.0)
Building wheels for collected packages: keras, theano
  Building wheel for keras (setup.py) ... done
  Created wheel for keras: filename=Keras-1.2.2-py3-none-any.whl size=210448 sha256=77dbae760dd1ba9e0d0a4d52ee0a6205dd46d950da73d2ab330404fa76b8f194
  Stored in directory: /home/jovyan/.cache/pip/wheels/e6/cb/36/559ef5c08ac134b88e39ac8e4342c5b8363b78919ac7053ef9
  Building wheel for theano (setup.py) ... done
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2669198 sha256=8bc1550b6bac9cd78d6586f6f740b4df47dc25246bd20ba56dfa928fc2351f0b
  Stored in directory: /home/jovyan/.cache/pip/wheels/7f/80/57/2970ddd2e4961d84fb0d58196f4965deead046d29e08693e73
Successfully built keras theano
Installing collected packages: google-cloud-core, google-cloud-bigquery, pandas, matplotlib, scipy, joblib, scikit-learn, tensorboard, tensorflow-estimator, tensorflow, theano, keras
  WARNING: The script tensorboard is installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts saved_model_cli, tensorboard, tf_upgrade_v2, tflite_convert, toco and toco_from_protos are installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts theano-cache and theano-nose are installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

google-cloud-storage 1.25.0 requires google-cloud-core<2.0dev,>=1.2.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
Successfully installed google-cloud-bigquery-1.6.0 google-cloud-core-0.28.1 joblib-0.16.0 keras-1.2.2 matplotlib-3.0.3 pandas-0.23.4 scikit-learn-0.22 scipy-1.2.1 tensorboard-2.0.2 tensorflow-2.0.0 tensorflow-estimator-2.0.1 theano-1.0.5

Restart the kernel before you proceed

In [1]:
import numpy as np
import pandas as  pd
import os
import matplotlib.pyplot as plt

# data encoding
from sklearn.preprocessing import LabelEncoder

# splitting the data
from sklearn.model_selection import train_test_split

# Standardization - feature scaling
from sklearn.preprocessing import StandardScaler

# Deep learning Libraries
import keras
from keras.models import Sequential
from keras.layers import Dense

# evaluating the mode
from sklearn.metrics import classification_report, confusion_matrix

Using TensorFlow backend.

In [2]:
DATA_DIR = 'data/'
data = pd.read_csv(DATA_DIR + "Churn_Modelling.csv")

In [3]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Data Preprocessing

In [4]:
X = data.iloc[:, 3:-1]
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71
6,822,France,Male,50,7,0.00,2,1,1,10062.80
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88
8,501,France,Male,44,4,142051.07,2,0,1,74940.50
9,684,France,Male,27,2,134603.88,1,1,1,71725.73
10,528,France,Male,31,6,102016.72,2,0,0,80181.12
11,497,Spain,Male,24,3,0.00,2,1,0,76390.01
12,476,France,Female,34,10,0.00,2,1,0,26260.98
13,549,France,Female,25,5,0.00,2,0,0,190857.79
14,635,Spain,Female,35,7,0.00,2,1,1,65951.65
15,616,Germany,Male,45,3,143129.41,2,0,1,64327.26
16,653,Germany,Male,58,1,132602.88,1,1,0,5097.67
17,549,Spain,Female,24,9,0.00,2,1,1,14406.41
18,587,Spain,Male,45,6,0.00,1,0,0,158684.81
19,726,France,Female,24,6,0.00,2,1,1,54724.03
20,732,France,Male,41,8,0.00,2,1,1,170886.17
21,636,Spain,Female,32,8,0.00,2,1,0,138555.46
22,510,Spain,Female,38,4,0.00,1,1,0,118913.53
23,669,France,Male,46,3,0.00,2,0,1,8487.75
24,846,France,Female,38,5,0.00,1,1,1,187616.16
25,577,France,Male,25,3,0.00,2,0,1,124508.29
26,756,Germany,Male,36,2,136815.64,1,1,1,170041.95
27,571,France,Male,44,9,0.00,2,0,0,38433.35
28,574,Germany,Female,43,3,141349.43,1,1,1,100187.43
29,411,France,Male,29,0,59697.17,2,1,1,53483.21
...,...,...,...,...,...,...,...,...,...,...
9970,518,France,Male,42,7,151027.05,2,1,0,119377.36
9971,833,France,Female,34,3,144751.81,1,0,0,166472.81
9972,758,France,Male,26,4,155739.76,1,1,0,171552.02
9973,611,France,Male,27,7,0.00,2,1,1,157474.10
9974,583,France,Male,33,7,122531.86,1,1,0,13549.24
9975,610,Germany,Male,50,1,113957.01,2,1,0,196526.55
9976,637,France,Female,33,7,103377.81,1,1,0,84419.78
9977,683,France,Female,32,9,0.00,2,1,1,24991.92
9978,774,France,Male,40,9,93017.47,2,1,0,191608.97
9979,677,France,Female,58,1,90022.85,1,0,1,2988.28
9980,741,Spain,Male,35,6,74371.49,1,0,0,99595.67
9981,498,Germany,Male,42,3,152039.70,1,1,1,53445.17
9982,655,Germany,Female,46,7,137145.12,1,1,0,115146.40
9983,613,France,Male,40,4,0.00,1,0,0,151325.24
9984,602,Germany,Male,35,7,90602.42,2,1,1,51695.41
9985,659,France,Male,36,6,123841.49,2,1,0,96833.00
9986,673,Germany,Male,47,1,183579.54,2,0,1,34047.54
9987,606,Spain,Male,30,8,180307.73,2,1,1,1914.41
9988,775,France,Male,30,4,0.00,2,1,0,49337.84
9989,841,Spain,Male,28,4,0.00,2,1,1,179436.60
9990,714,Germany,Male,33,3,35016.60,1,1,0,53667.08
9991,597,France,Female,53,4,88381.21,1,1,0,69384.71
9992,726,Spain,Male,36,2,0.00,1,1,0,195192.40
9993,644,France,Male,28,7,155060.41,1,1,0,29179.52
9994,800,France,Female,29,2,0.00,2,0,0,167773.55
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [5]:
y = data.iloc[:,-1:]
y

      Exited
0          1
1          0
2          1
3          0
4          0
5          1
6          0
7          1
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         1
17         0
18         0
19         0
20         0
21         0
22         1
23         0
24         0
25         0
26         0
27         0
28         0
29         0
...      ...
9970       0
9971       0
9972       0
9973       0
9974       0
9975       1
9976       0
9977       0
9978       0
9979       0
9980       0
9981       1
9982       1
9983       0
9984       0
9985       0
9986       0
9987       0
9988       0
9989       0
9990       0
9991       1
9992       0
9993       0
9994       0
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 1 columns]

#### Data encoding

In [6]:
# encoding country
encoder_X_1= LabelEncoder()
X.iloc[:,1] = encoder_X_1.fit_transform(X.iloc[:,1])

In [7]:
# encoding gender
encoder_X_2= LabelEncoder()
X.iloc[:,2] = encoder_X_2.fit_transform(X.iloc[:,2])

In [8]:
# we would also use the dummy variable because they are norminal variables


dummy = pd.get_dummies(X["Geography"], prefix = ['Geography'],drop_first=True)
X=pd.concat([X,dummy], axis = 1)
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,['Geography']_1,['Geography']_2
0,619,0,0,42,2,0.00,1,1,1,101348.88,0,0
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0,1
2,502,0,0,42,8,159660.80,3,1,0,113931.57,0,0
3,699,0,0,39,1,0.00,2,0,0,93826.63,0,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0,1

In [9]:
X=X.drop(columns = ['Geography'], axis = 1)

In [10]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,['Geography']_1,['Geography']_2
0,619,0,42,2,0.00,1,1,1,101348.88,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,1
5,645,1,44,8,113755.78,2,1,0,149756.71,0,1
6,822,1,50,7,0.00,2,1,1,10062.80,0,0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,0
10,528,1,31,6,102016.72,2,0,0,80181.12,0,0
11,497,1,24,3,0.00,2,1,0,76390.01,0,1
12,476,0,34,10,0.00,2,1,0,26260.98,0,0
13,549,0,25,5,0.00,2,0,0,190857.79,0,0
14,635,0,35,7,0.00,2,1,1,65951.65,0,1
15,616,1,45,3,143129.41,2,0,1,64327.26,1,0
16,653,1,58,1,132602.88,1,1,0,5097.67,1,0
17,549,0,24,9,0.00,2,1,1,14406.41,0,1
18,587,1,45,6,0.00,1,0,0,158684.81,0,1
19,726,0,24,6,0.00,2,1,1,54724.03,0,0
20,732,1,41,8,0.00,2,1,1,170886.17,0,0
21,636,0,32,8,0.00,2,1,0,138555.46,0,1
22,510,0,38,4,0.00,1,1,0,118913.53,0,1
23,669,1,46,3,0.00,2,0,1,8487.75,0,0
24,846,0,38,5,0.00,1,1,1,187616.16,0,0
25,577,1,25,3,0.00,2,0,1,124508.29,0,0
26,756,1,36,2,136815.64,1,1,1,170041.95,1,0
27,571,1,44,9,0.00,2,0,0,38433.35,0,0
28,574,0,43,3,141349.43,1,1,1,100187.43,1,0
29,411,1,29,0,59697.17,2,1,1,53483.21,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9970,518,1,42,7,151027.05,2,1,0,119377.36,0,0
9971,833,0,34,3,144751.81,1,0,0,166472.81,0,0
9972,758,1,26,4,155739.76,1,1,0,171552.02,0,0
9973,611,1,27,7,0.00,2,1,1,157474.10,0,0
9974,583,1,33,7,122531.86,1,1,0,13549.24,0,0
9975,610,1,50,1,113957.01,2,1,0,196526.55,1,0
9976,637,0,33,7,103377.81,1,1,0,84419.78,0,0
9977,683,0,32,9,0.00,2,1,1,24991.92,0,0
9978,774,1,40,9,93017.47,2,1,0,191608.97,0,0
9979,677,0,58,1,90022.85,1,0,1,2988.28,0,0
9980,741,1,35,6,74371.49,1,0,0,99595.67,0,1
9981,498,1,42,3,152039.70,1,1,1,53445.17,1,0
9982,655,0,46,7,137145.12,1,1,0,115146.40,1,0
9983,613,1,40,4,0.00,1,0,0,151325.24,0,0
9984,602,1,35,7,90602.42,2,1,1,51695.41,1,0
9985,659,1,36,6,123841.49,2,1,0,96833.00,0,0
9986,673,1,47,1,183579.54,2,0,1,34047.54,1,0
9987,606,1,30,8,180307.73,2,1,1,1914.41,0,1
9988,775,1,30,4,0.00,2,1,0,49337.84,0,0
9989,841,1,28,4,0.00,2,1,1,179436.60,0,1
9990,714,1,33,3,35016.60,1,1,0,53667.08,1,0
9991,597,0,53,4,88381.21,1,1,0,69384.71,0,0
9992,726,1,36,2,0.00,1,1,0,195192.40,0,1
9993,644,1,28,7,155060.41,1,1,0,29179.52,0,0
9994,800,0,29,2,0.00,2,0,0,167773.55,0,0
9995,771,1,39,5,0.00,2,1,0,96270.64,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,0

## Install Kubeflow pipelines SDK

In [11]:
!pip3 install kfp --upgrade --user

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting kfp
  Downloading kfp-1.0.0.tar.gz (116 kB)
     |████████████████████████████████| 116 kB 2.8 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python3.6/dist-packages (from kfp) (5.3)
Requirement already satisfied, skipping upgrade: google-cloud-storage>=1.13.0 in /usr/local/lib/python3.6/dist-packages (from kfp) (1.25.0)
Requirement already satisfied, skipping upgrade: kubernetes<12.0.0,>=8.0.0 in /usr/local/lib/python3.6/dist-packages (from kfp) (10.0.1)
Requirement already satisfied, skipping upgrade: google-auth>=1.6.1 in /usr/local/lib/python3.6/dist-packages (from kfp) (1.10.0)
Collecting requests_toolbelt>=0.8.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 3.3 MB/s  eta 0:00:01
Requirement already satisfied, skipping upgrade: cloudpickle in /usr/local/lib/python3.6/dist-packages (from kfp) (1.2.2)
Collecting kfp-server-api<2.0.0,>=0.2.5
  Downloading kfp-server-api-1.0.0.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 694 kB/s  eta 0:00:01
Requirement already satisfied, skipping upgrade: jsonschema>=3.0.1 in /usr/local/lib/python3.6/dist-packages (from kfp) (3.2.0)
Collecting tabulate
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.2 MB/s  eta 0:00:01
Collecting Deprecated
  Downloading Deprecated-1.2.10-py2.py3-none-any.whl (8.7 kB)
Collecting strip-hints
  Downloading strip-hints-0.1.9.tar.gz (30 kB)
Requirement already satisfied, skipping upgrade: google-resumable-media<0.6dev,>=0.5.0 in /usr/local/lib/python3.6/dist-packages (from google-cloud-storage>=1.13.0->kfp) (0.5.0)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Downloading google_cloud_core-1.4.1-py2.py3-none-any.whl (26 kB)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.3 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (2.8.1)
Requirement already satisfied, skipping upgrade: urllib3>=1.24.2 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (1.25.7)
Requirement already satisfied, skipping upgrade: requests-oauthlib in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (1.3.0)
Requirement already satisfied, skipping upgrade: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (0.57.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (2.22.0)
Requirement already satisfied, skipping upgrade: setuptools>=21.0.0 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (44.0.0)
Requirement already satisfied, skipping upgrade: certifi>=14.05.14 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (2019.11.28)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from kubernetes<12.0.0,>=8.0.0->kfp) (1.13.0)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth>=1.6.1->kfp) (4.0.0)
Requirement already satisfied, skipping upgrade: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth>=1.6.1->kfp) (4.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth>=1.6.1->kfp) (0.2.8)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->kfp) (1.4.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->kfp) (19.3.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->kfp) (0.15.7)
Requirement already satisfied, skipping upgrade: wrapt<2,>=1.10 in /usr/local/lib/python3.6/dist-packages (from Deprecated->kfp) (1.11.2)
Requirement already satisfied, skipping upgrade: wheel in /usr/lib/python3/dist-packages (from strip-hints->kfp) (0.30.0)
Collecting google-api-core<2.0.0dev,>=1.19.0
  Downloading google_api_core-1.22.1-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 10.6 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib->kubernetes<12.0.0,>=8.0.0->kfp) (3.1.0)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests->kubernetes<12.0.0,>=8.0.0->kfp) (2.6)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kubernetes<12.0.0,>=8.0.0->kfp) (3.0.4)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<4.1,>=3.1.4->google-auth>=1.6.1->kfp) (0.4.8)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.0.1->kfp) (0.6.0)
Requirement already satisfied, skipping upgrade: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.19.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.13.0->kfp) (1.51.0)
Collecting protobuf>=3.12.0
  Downloading protobuf-3.13.0-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 33.2 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: pytz in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0dev,>=1.19.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.13.0->kfp) (2019.3)
Requirement already satisfied, skipping upgrade: more-itertools in /usr/local/lib/python3.6/dist-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->jsonschema>=3.0.1->kfp) (8.0.2)
Building wheels for collected packages: kfp, kfp-server-api, strip-hints
  Building wheel for kfp (setup.py) ... done
  Created wheel for kfp: filename=kfp-1.0.0-py3-none-any.whl size=160799 sha256=27c2e80647a3c91c388c6c0d70a5d258a4d44e33998349afe5324a201ec287bf
  Stored in directory: /home/jovyan/.cache/pip/wheels/a1/4d/1d/532b25d0ea5bf28d352c8973b8ce9b1d7f8f5220b236af1c62
  Building wheel for kfp-server-api (setup.py) ... done
  Created wheel for kfp-server-api: filename=kfp_server_api-1.0.0-py3-none-any.whl size=105028 sha256=405869591560b601364c2a19276e797c5d0a268c717e5afc5eb52b69bfcf8398
  Stored in directory: /home/jovyan/.cache/pip/wheels/c9/65/08/c985cd0191974934cd16f91b4c43a83779b90e87c0773ada32
  Building wheel for strip-hints (setup.py) ... done
  Created wheel for strip-hints: filename=strip_hints-0.1.9-py2.py3-none-any.whl size=24671 sha256=34184e4e1cbc204f2b1013bcd6afbb9c5d410545f28881bbf36e42ad03d24f69
  Stored in directory: /home/jovyan/.cache/pip/wheels/21/6d/fa/7ed7c0560e1ef39ebabd5cc0241e7fca711660bae1ad752e2b
Successfully built kfp kfp-server-api strip-hints
Installing collected packages: requests-toolbelt, kfp-server-api, tabulate, click, Deprecated, strip-hints, kfp, protobuf, google-api-core, google-cloud-core
  WARNING: The script tabulate is installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script strip-hints is installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts dsl-compile and kfp are installed in '/home/jovyan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: google-cloud-core
    Found existing installation: google-cloud-core 0.28.1
    Uninstalling google-cloud-core-0.28.1:
      Successfully uninstalled google-cloud-core-0.28.1
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

google-cloud-bigquery 1.6.0 requires google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 1.4.1 which is incompatible.
google-api-core 1.22.1 requires google-auth<2.0dev,>=1.19.1, but you'll have google-auth 1.10.0 which is incompatible.
Successfully installed Deprecated-1.2.10 click-7.1.2 google-api-core-1.22.1 google-cloud-core-1.4.1 kfp-1.0.0 kfp-server-api-1.0.0 protobuf-3.13.0 requests-toolbelt-0.9.1 strip-hints-0.1.9 tabulate-0.8.7

Check if the install was successful:

In [12]:
!which dsl-compile

## Build the Components

In [13]:
# Import Kubeflow SDK
import kfp
import kfp.dsl as dsl
import kfp.components as comp


import pickle
import tensorflow as tf
from tensorflow.python import keras

In [14]:
# Download the dataset and split into training and test data. 
DATA_DIR = 'data/'
data = pd.read_csv(DATA_DIR + "Churn_Modelling.csv")
X_train,X_test,y_train,y_test = train_test_split( X,y, test_size=0.2, random_state = 0)
# Normalize the data.
sc =StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

y_train = y_train.values
y_test = y_test.values
def train(data_path, model_file):


    # Define the model using Keras.
    classifier = keras.models.Sequential()
    classifier.add(keras.layers.Dense(units =6, activation='relu', input_dim=11))
    classifier.add(keras.layers.Dense(units =6, activation='relu'))
    classifier.add(keras.layers.Dense(units =1, activation='sigmoid'))

    classifier.summary()

    classifier.compile(optimizer = 'adam', loss='binary_crossentropy' 
                    , metrics =['accuracy'])

    return classifier

In [15]:
# Run a training job with specified number of epochs
classifier.fit(X_train, y_train, batch_size=10 , epochs=100)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 72
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________
Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 210us/sample - loss: 0.5415 - accuracy: 0.7763
Epoch 2/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.4450 - accuracy: 0.8040
Epoch 3/100
8000/8000 [==============================] - 1s 130us/sample - loss: 0.4220 - accuracy: 0.8104
Epoch 4/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.4081 - accuracy: 0.8186
Epoch 5/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3908 - accuracy: 0.8310
Epoch 6/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3740 - accuracy: 0.8443
Epoch 7/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3620 - accuracy: 0.8530
Epoch 8/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3550 - accuracy: 0.8584
Epoch 9/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3506 - accuracy: 0.8596
Epoch 10/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3484 - accuracy: 0.8594
Epoch 11/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3472 - accuracy: 0.8585
Epoch 12/100
8000/8000 [==============================] - 1s 123us/sample - loss: 0.3457 - accuracy: 0.8594
Epoch 13/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3447 - accuracy: 0.8616
Epoch 14/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3431 - accuracy: 0.8605
Epoch 15/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3422 - accuracy: 0.8611
Epoch 16/100
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3412 - accuracy: 0.8629
Epoch 17/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3401 - accuracy: 0.8643
Epoch 18/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3392 - accuracy: 0.8612
Epoch 19/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3391 - accuracy: 0.8636
Epoch 20/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3382 - accuracy: 0.8630
Epoch 21/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3382 - accuracy: 0.8641
Epoch 22/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3374 - accuracy: 0.8644
Epoch 23/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3371 - accuracy: 0.8637
Epoch 24/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3373 - accuracy: 0.8644
Epoch 25/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3369 - accuracy: 0.8636
Epoch 26/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3361 - accuracy: 0.8658
Epoch 27/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3363 - accuracy: 0.8644
Epoch 28/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3362 - accuracy: 0.8636
Epoch 29/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3358 - accuracy: 0.8660
Epoch 30/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3357 - accuracy: 0.8633
Epoch 31/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3354 - accuracy: 0.8660 -
Epoch 32/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3353 - accuracy: 0.8637
Epoch 33/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3352 - accuracy: 0.8648
Epoch 34/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3349 - accuracy: 0.8637
Epoch 35/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3350 - accuracy: 0.8656
Epoch 36/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3350 - accuracy: 0.8650
Epoch 37/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3340 - accuracy: 0.8640
Epoch 38/100
8000/8000 [==============================] - 1s 123us/sample - loss: 0.3348 - accuracy: 0.8637
Epoch 39/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3337 - accuracy: 0.8654
Epoch 40/100
8000/8000 [==============================] - 1s 131us/sample - loss: 0.3337 - accuracy: 0.8648
Epoch 41/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3337 - accuracy: 0.8658
Epoch 42/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3339 - accuracy: 0.8656
Epoch 43/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3330 - accuracy: 0.8669
Epoch 44/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3339 - accuracy: 0.8662
Epoch 45/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3335 - accuracy: 0.8659
Epoch 46/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3332 - accuracy: 0.8652
Epoch 47/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3333 - accuracy: 0.8659
Epoch 48/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3335 - accuracy: 0.8649
Epoch 49/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3335 - accuracy: 0.8651
Epoch 50/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3325 - accuracy: 0.8659
Epoch 51/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3326 - accuracy: 0.8637
Epoch 52/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3328 - accuracy: 0.8671
Epoch 53/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3330 - accuracy: 0.8674
Epoch 54/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3328 - accuracy: 0.8662
Epoch 55/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3325 - accuracy: 0.8656
Epoch 56/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3329 - accuracy: 0.8658
Epoch 57/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3322 - accuracy: 0.8673
Epoch 58/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3324 - accuracy: 0.8660
Epoch 59/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3317 - accuracy: 0.8671
Epoch 60/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3316 - accuracy: 0.8666
Epoch 61/100
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3321 - accuracy: 0.8665
Epoch 62/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3319 - accuracy: 0.8658
Epoch 63/100
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3319 - accuracy: 0.8660
Epoch 64/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3311 - accuracy: 0.8673
Epoch 65/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3315 - accuracy: 0.8675
Epoch 66/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3316 - accuracy: 0.8654
Epoch 67/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3315 - accuracy: 0.8677
Epoch 68/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3314 - accuracy: 0.8680
Epoch 69/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3313 - accuracy: 0.8668
Epoch 70/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3315 - accuracy: 0.8673
Epoch 71/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3314 - accuracy: 0.8690
Epoch 72/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3311 - accuracy: 0.8652
Epoch 73/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3314 - accuracy: 0.8675
Epoch 74/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3305 - accuracy: 0.8666
Epoch 75/100
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3310 - accuracy: 0.8679
Epoch 76/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3307 - accuracy: 0.8671
Epoch 77/100
8000/8000 [==============================] - 1s 133us/sample - loss: 0.3306 - accuracy: 0.8673
Epoch 78/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3309 - accuracy: 0.8660
Epoch 79/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3310 - accuracy: 0.8660
Epoch 80/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3313 - accuracy: 0.8679
Epoch 81/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3308 - accuracy: 0.8664
Epoch 82/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3302 - accuracy: 0.8673
Epoch 83/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3307 - accuracy: 0.8681
Epoch 84/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3309 - accuracy: 0.8668
Epoch 85/100
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3312 - accuracy: 0.8640
Epoch 86/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3301 - accuracy: 0.8683
Epoch 87/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3309 - accuracy: 0.8645
Epoch 88/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3304 - accuracy: 0.8662
Epoch 89/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3306 - accuracy: 0.8666
Epoch 90/100
8000/8000 [==============================] - 1s 131us/sample - loss: 0.3306 - accuracy: 0.8665
Epoch 91/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3302 - accuracy: 0.8673
Epoch 92/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3307 - accuracy: 0.8658
Epoch 93/100
8000/8000 [==============================] - 1s 124us/sample - loss: 0.3306 - accuracy: 0.8679
Epoch 94/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3309 - accuracy: 0.8689
Epoch 95/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3300 - accuracy: 0.8662
Epoch 96/100
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3302 - accuracy: 0.8673
Epoch 97/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3304 - accuracy: 0.8660
Epoch 98/100
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3305 - accuracy: 0.8664
Epoch 99/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3304 - accuracy: 0.8674
Epoch 100/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3299 - accuracy: 0.8655

In [16]:
#Evaluate the model and print the results
test_loss, test_acc = classifier.evaluate(X_test,  y_test, verbose=0)
print('Test accuracy:', test_acc)

#Save the model to the designated 
classifier.save(os.path.join("trained_model"))

#Save the test_data as a pickle file to be used by the predict component.
with open(os.path.join("test_data"), 'wb') as f:
    pickle.dump((X_test,  y_test), f)

Test accuracy: 0.8645
WARNING:tensorflow:From /home/jovyan/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: trained_model/assets

In [17]:
def predict(data_path, model_file, churn_rate):
    
    # Load the saved Keras model
    classifier = keras.models.load_model("trained_model")

    # Load and unpack the test_data
    with open(os.path.join("test_data"),'rb') as f:
        test_data = pickle.load(f)
    # Separate the test_images from the test_labels.
    X_test,  y_test = test_data

    churn_rate = int(churn_rate)

    # make predictions.
    y_pred = classifier.predict(X_test)


    # create a threshold for the confution matrics
    y_pred=(y_pred>0.5)
    
    with open(f'result.txt', 'w') as result:
        result.write(" Prediction: {} ".format(y_pred))
    
    print('Prediction has be saved successfully!')

In [19]:
# Create train and predict lightweight components.
train_op = comp.func_to_container_op(train)
predict_op = comp.func_to_container_op(predict)

## Build Kubeflow Pipeline

In [20]:
#Create a client to enable communication with the Pipelines API server.
client = kfp.Client()

In [21]:
# Define the pipeline
@dsl.pipeline(
   name='Customer Churn Pipeline',
   description='An ML pipeline that performs Customer Churn model training and prediction.'
)

# Define parameters to be fed into pipeline
def churn_container_pipeline(
    data_path: str = DATA_PATH,
    model_file: str= MODEL_FILE, 
    churn_rate: int = CHURN_RATE
):
    
    # Define volume to share data between components.
    vop = dsl.VolumeOp(
    name="create_volume",
    resource_name="data-volume", 
    size="4Gi", 
    modes=dsl.VOLUME_MODE_RWM)
    
    # Create churn training component.
    churn_training_container = train_op(data_path, model_file) \
                                    .add_pvolumes({data_path: vop.volume})

    # Create Churn prediction component.
    churn_predict_container = predict_op(data_path, model_file, churn_rate) \
                                    .add_pvolumes({data_path: churn_training_container.pvolume})
    
    # Print the result of the prediction
    churn_result_container = dsl.ContainerOp(
        name="print_prediction",
        image='gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0',
        pvolumes={data_path: churn_predict_container.pvolume},
        arguments=['cat', f'{data_path}/result.txt']
    )

## Run the Pipeline

In [22]:
DATA_PATH = '/churn'
MODEL_PATH='churn_classifier.h5'
# An integer representing an image from the test set that the model will attempt to predict the label for.
CHURN_RATE = 3

In [23]:
pipeline_func = churn_container_pipeline

In [24]:
experiment_name = 'costumer_churn_kubeflow'
run_name = pipeline_func.__name__ + ' run'

arguments = {"data_path":DATA_PATH,
             "model_file":MODEL_PATH,
             "churn_rate": CHURN_RATE}

# Compile pipeline to generate compressed YAML definition of the pipeline.
kfp.compiler.Compiler().compile(pipeline_func,  
  '{}.zip'.format(experiment_name))

# Submit pipeline directly from pipeline function
run_result = client.create_run_from_pipeline_func(pipeline_func, 
                                                  experiment_name=experiment_name, 
                                                  run_name=run_name, 
                                                  arguments=arguments)